In [1]:
import pandas as pd

data_url = 'https://datamarket.es/media/samples/catastro-sample.csv'

df = pd.read_csv(data_url)

In [2]:
#df
for col in df.columns:
    print(col)

area
autonomous_region
description
has_doorman
has_garden
has_lift
has_parking
has_storage
has_swimming_pool
is_residential
latitude
longitude
neighbors_per_floor
number
postal_code
province
reference
street
area_item
floor
typology_item
door
total_floors
town
typology
year_built
shared_quota

In [3]:
df1 = df[['area','province', 'year_built','has_swimming_pool']]
df1

        area  province  year_built has_swimming_pool
0        130    Madrid      2012.0             False
1        130    Madrid      2012.0             False
2         82    Madrid      1925.0             False
3        165    Madrid      2006.0             False
4      14144    Madrid         NaN               NaN
...      ...       ...         ...               ...
59995    214  Asturias      1880.0             False
59996    251  Asturias      1930.0             False
59997     27  Asturias      2008.0             False
59998     92  Asturias      1974.0             False
59999    151  Asturias      2003.0             False

[60000 rows x 4 columns]

In [4]:
df1 = df1.dropna()
df1

       area  province  year_built has_swimming_pool
0       130    Madrid      2012.0             False
1       130    Madrid      2012.0             False
2        82    Madrid      1925.0             False
3       165    Madrid      2006.0             False
5       104    Madrid      2004.0              True
...     ...       ...         ...               ...
59995   214  Asturias      1880.0             False
59996   251  Asturias      1930.0             False
59997    27  Asturias      2008.0             False
59998    92  Asturias      1974.0             False
59999   151  Asturias      2003.0             False

[53392 rows x 4 columns]

In [5]:
df2 = df1.head(100)
df2

     area province  year_built has_swimming_pool
0     130   Madrid      2012.0             False
1     130   Madrid      2012.0             False
2      82   Madrid      1925.0             False
3     165   Madrid      2006.0             False
5     104   Madrid      2004.0              True
..    ...      ...         ...               ...
113    33   Madrid      1966.0             False
114   144   Madrid      1955.0             False
115   108   Madrid      1975.0             False
116    95   Madrid      1985.0             False
117   101   Madrid      2010.0             False

[100 rows x 4 columns]

In [6]:
# df["has_swimming_pool"].replace({"False": "0", "True": "1"},inplace=True)
# df
df['has_swimming_pool'] = df['has_swimming_pool'].map({'True': 1, 'False': 0})
df

,area,autonomous_region,description,has_doorman,has_garden,has_lift,has_parking,has_storage,has_swimming_pool,is_residential,...,street,area_item,floor,typology_item,door,total_floors,town,typology,year_built,shared_quota
0,130,"Madrid, Comunidad de",Esc.1 Bajo B,True,False,True,True,True,NaN,True,...,Calle Valle Del Baztan,11,-1,AAP,5,5.0,TorrejÃ³n de Ardoz,V,2012.0,0.0006
1,130,"Madrid, Comunidad de",Esc.7 3Âº B,True,False,True,True,True,NaN,True,...,Calle Valle Del Baztan,4,-1,AAL,111,5.0,TorrejÃ³n de Ardoz,V,2012.0,0.0002
2,82,"Madrid, Comunidad de",2Âº 03,False,False,False,False,False,NaN,True,...,Calle Santa Juliana,77,02,V,03,6.0,Madrid,V,1925.0,0.0452
3,165,"Madrid, Comunidad de",Inmueble,False,True,False,False,True,NaN,True,...,Calle Sicomoro (Del),58,01,V,01,3.0,MÃ³stoles,V,2006.0,0.3515
4,14144,"Madrid, Comunidad de",Inmueble,NaN,NaN,NaN,NaN,NaN,NaN,False,...,Calle Alcala,1040,02,P,01,NaN,Madrid,O,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,214,"Asturias, Principado de",Inmueble,False,True,False,False,True,NaN,True,...,Poblado Vis,35,01,AAL,02,2.0,Amieva,V,1880.0,0.1636
59996,251,"Asturias, Principado de",Inmueble,False,True,False,False,True,NaN,True,...,Calle Francisco Garcia,50,00,V,01,1.0,Langreo,V,1930.0,0.1992
59997,27,"Asturias, Principado de",-1Âº 06,False,False,True,True,True,NaN,True,...,Calle Francisco Pintado Fe,15,-1,AAP,06,6.0,Langreo,A,2008.0,NaN
59998,92,"Asturias, Principado de",Esc.1 5Âº 0B,False,False,True,False,False,NaN,True,...,Calle Ingeniero Fernando Cas,82,05,V,0B,6.0,Langreo,V,1974.0,0.0322
59999,151,"Asturias, Principado de",Esc.1 1Âº A,False,False,True,True,True,NaN,True,...,Calle Llaviada,92,01,V,A,6.0,Oviedo,V,2003.0,0.0107

In [7]:
X_ = df2.drop('has_swimming_pool', axis=1)
X_.shape

(100, 3)

In [8]:
y_ = df2['has_swimming_pool']
y_.shape

(100,)

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( X_, y_, test_size=.2, random_state=4)
x_train.shape
#y_train.shape

(80, 3)

In [10]:
!pip install qiskit-machine-learning

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting qiskit-machine-learning
  Downloading qiskit_machine_learning-0.4.0-py3-none-any.whl (126 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 126 kB 20.4 MB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (1.21.6)
Requirement already satisfied: scipy>=1.4 in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (1.7.3)
Requirement already satisfied: dill>=0.3.4 in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (0.3.5.1)
Requirement already satisfied: setuptools>=40.1.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (57.4.0)
Collecting qiskit-terra>=0.20.0
  Downloading qiskit_terra-0.21.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.7 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 6.7 MB 47.6 MB/s
Requirement already satisfied: psutil>=5 in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (5.4.8)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (1.0.2)
Requirement already satisfied: fastdtw in /usr/local/lib/python3.7/dist-packages (from qiskit-machine-learning) (0.3.4)
Collecting tweedledum<2.0,>=1.1
  Downloading tweedledum-1.1.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (943 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 943 kB 23.0 MB/s
Collecting stevedore>=3.0.0
  Downloading stevedore-3.5.0-py3-none-any.whl (49 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 49 kB 5.6 MB/s
Collecting shared-memory38
  Downloading shared_memory38-0.1.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (25 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.20.0->qiskit-machine-learning) (4.1.1)
Collecting ply>=3.10
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 49 kB 5.0 MB/s
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.20.0->qiskit-machine-learning) (2.8.2)
Collecting symengine>=0.9
  Downloading symengine-0.9.2-cp37-cp37m-manylinux2010_x86_64.whl (37.5 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 37.5 MB 2.3 MB/s
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.20.0->qiskit-machine-learning) (1.7.1)
Collecting retworkx>=0.11.0
  Downloading retworkx-0.11.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1.6 MB 36.5 MB/s
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.8.0->qiskit-terra>=0.20.0->qiskit-machine-learning) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->qiskit-machine-learning) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->qiskit-machine-learning) (1.1.0)
Collecting pbr!=2.1.0,>=2.0.0
  Downloading pbr-5.9.0-py2.py3-none-any.whl (112 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 112 kB 19.8 MB/s
Requirement already satisfied: importlib-metadata>=1.7.0 in /usr/local/lib/python3.7/dist-packages (from stevedore>=3.0.0->qiskit-terra>=0.20.0->qiskit-machine-learning) (4.12.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.7.0->stevedore>=3.0.0->qiskit-terra>=0.20.0->qiskit-machine-learning) (3.8.1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.7/dist-packages (from sympy>=1.3->qiskit-terra>=0.20.0->qiskit-machine-learning) (1.2.1)
Installing collected packages: pbr, tweedledum, symengine, stevedore, shared-memory38, retworkx, ply, qiskit-terra, qiskit-machine-learning
Successfully installed pbr-5.9.0 ply-3.11 qiskit-machine-learning-0.4.0 qiskit-terra-0.21.1 retworkx-0.11.0 shared-memory38-0.1.2 stevedore-3.5.0 symengine-0.9.2 tweedledum-1.1.1

In [11]:
from qiskit import BasicAer

backend = BasicAer.get_backend('statevector_simulator')

In [12]:
!pip install qiskit-ibmq-provider

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting qiskit-ibmq-provider
  Downloading qiskit_ibmq_provider-0.19.2-py3-none-any.whl (240 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 240 kB 27.5 MB/s
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-ibmq-provider) (2.8.2)
Collecting websocket-client>=1.0.1
  Downloading websocket_client-1.3.3-py3-none-any.whl (54 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 54 kB 3.2 MB/s
Requirement already satisfied: requests>=2.19 in /usr/local/lib/python3.7/dist-packages (from qiskit-ibmq-provider) (2.23.0)
Collecting requests-ntlm>=1.1.0
  Downloading requests_ntlm-1.1.0-py2.py3-none-any.whl (5.7 kB)
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from qiskit-ibmq-provider) (1.24.3)
Collecting websockets>=10.0
  Downloading websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 112 kB 49.8 MB/s
Requirement already satisfied: qiskit-terra>=0.18.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-ibmq-provider) (0.21.1)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.7/dist-packages (from qiskit-ibmq-provider) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.8.0->qiskit-ibmq-provider) (1.15.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (4.1.1)
Requirement already satisfied: symengine>=0.9 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (0.9.2)
Requirement already satisfied: ply>=3.10 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (3.11)
Requirement already satisfied: shared-memory38 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (0.1.2)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (1.7.3)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (0.3.5.1)
Requirement already satisfied: psutil>=5 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (5.4.8)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (1.7.1)
Requirement already satisfied: retworkx>=0.11.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (0.11.0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (3.5.0)
Requirement already satisfied: tweedledum<2.0,>=1.1 in /usr/local/lib/python3.7/dist-packages (from qiskit-terra>=0.18.0->qiskit-ibmq-provider) (1.1.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19->qiskit-ibmq-provider) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19->qiskit-ibmq-provider) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19->qiskit-ibmq-provider) (2022.6.15)
Collecting ntlm-auth>=1.0.2
  Downloading ntlm_auth-1.5.0-py2.py3-none-any.whl (29 kB)
Collecting cryptography>=1.3
  Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4.1 MB 32.2 MB/s
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider) (2.21)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from stevedore>=3.0.0->qiskit-terra>=0.18.0->qiskit-ibmq-provider) (5.9.0)
Requirement already satisfied: importlib-metadata>=1.7.0 in /usr/local/lib/python3.7/dist-packages (from stevedore>=3.0.0->qiskit-terra>=0.18.0->qiskit-ibmq-provider) (4.12.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.7.0->stevedore>=3.0.0->qiskit-terra>=0.18.0->qiskit-ibmq-provider) (3.8.1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.7/dist-packages (from sympy>=1.3->qiskit-terra>=0.18.0->qiskit-ibmq-provider) (1.2.1)
Installing collected packages: ntlm-auth, cryptography, websockets, websocket-client, requests-ntlm, qiskit-ibmq-provider
Successfully installed cryptography-37.0.4 ntlm-auth-1.5.0 qiskit-ibmq-provider-0.19.2 requests-ntlm-1.1.0 websocket-client-1.3.3 websockets-10.3

In [13]:
from qiskit import IBMQ
IBMQ.save_account('763f3d42e3016709be48fe645fc6bc9eb32905081ebac3f67c123f8278785d9231ee392a323554b6e0efac1c36d7cd24ef5ab2f506cef6ff3d1fe69a4d02b56f')

In [14]:
IBMQ.load_account()

In [15]:
provider = IBMQ.load_account()
#prvdr=IBMQ.get_provider('ibm-q')
backend=provider.get_backend('ibmq_belem')
# quantum_computer_id = 'quantum_computer_id'

# backend = provider.get_backend(quantum_computer_id)

ibmqfactory.load_account:WARNING:2022-08-05 03:30:40,860: Credentials are already in use. The existing account in the session will be replaced.

In [16]:
from qiskit.utils import QuantumInstance

quantum_instance = QuantumInstance(backend)

In [17]:
num_qubits = 4

In [18]:
from qiskit.circuit.library import ZFeatureMap

feature_map = ZFeatureMap(feature_dimension=num_qubits)

In [19]:
from qiskit_machine_learning.kernels import QuantumKernel

qkernel = QuantumKernel(feature_map=feature_map, quantum_instance=quantum_instance)

In [20]:
from qiskit_machine_learning.algorithms import QSVC

qsvc = QSVC(quantum_kernel=qkernel)

#qsvc.fit(x_train, y_train)